version: 1.0.{build}
branches:
  only:
    - master
    - AppVeyorSikuli

clone_depth: 5
shallow_clone: true
skip_tags: true
skip_commits:
  message: /SkipCI.*/

cache:
  - sikulixsetup-1.1.0.jar
  - ffmpeg-20160527-git-d970f7b-win32-static.7z
  - VCForPython27.msi
build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

init:
  - "@ECHO AppVeyor CI run started!"

install:
  - "@ECHO AppVeyor CI installation started!"
  - bootstrap.bat

test_script:
  - "@ECHO AppVeyor CI test started!"
  - activate hasal-env
  - python scripts\cv2_checker.py
  - python runtest.py -h
  - ffmpeg -h

on_success:
  - cmd: echo AppVeyor run was successful!
on_failure:
  - cmd: echo AppVeyor run FAILED!
